### PR TITLE
Sending pictures

### PR DESCRIPTION
**Pull request by unsanded**
Heey, i liked the app, but i just missed the the option to send pictures. So i made it. Just see if you like it, and it might need some polishing here and there, but it works for me.

### CODE REVIEW

**Comment by markussammallahti** [comment]
I need to try this out with devices and I'll add some comments later.

**Comment by unsanded** [comment]
Ok, thanks. I am using it myself now without problem, and it works fine. There is just no feedback yet while uploading. So it just hangs for a while. But i didn't quite know of a way to implement this gracefully without changing the whole structure.

**Comment by markussammallahti** [comment]
This works quite nicely. There definitely needs to be upload indicator or something. I'll merge this as is and I'll figure out a nice way to handle upload feedback.

**Comment by modulebaan** [comment]
It this already available in the Slackfish version from the Jolla Store? 
If not, how can I compile the code without creating a new Slack app? I just got it working on my Slack team channel and I can't ask my employer again to approve a new app...

**Comment by markussammallahti** [comment]
The current version in Jolla Store does not have upload support. I can create a release that has the upload support.

**Comment by modulebaan** [comment]
That would be nice! Picture upload is really handy :+1:

**Pull request merged**
